export enum UserRole {
  PLAYER = "player",
  GM = "gm",
}

export enum ScreenEnum {
  LOGIN = "LOGIN",
  EMAIL_LOGIN = "EMAIL_LOGIN",
  EMAIL_SIGNUP = "EMAIL_SIGNUP",
  HOME = "HOME",
  ACCESS_SERVER = "ACCESS_SERVER",
  CREATE_SERVER = "CREATE_SERVER",
  GM_LOBBY = "GM_LOBBY",
  PLAYER_LOBBY = "PLAYER_LOBBY",
  GAME_IN_PROGRESS_PLAYER = "GAME_IN_PROGRESS_PLAYER",
  GAME_IN_PROGRESS_GM = "GAME_IN_PROGRESS_GM",
  CHARACTER_CREATE_THEME = "CHARACTER_CREATE_THEME",
  CHARACTER_CREATE_DETAILS = "CHARACTER_CREATE_DETAILS",
  CHARACTER_CREATE_NAME_DESC_SKILL = "CHARACTER_CREATE_NAME_DESC_SKILL",
  CHARACTER_SHEET = "CHARACTER_SHEET",
}

export enum CharacterCreationStep {
  THEME,
  DETAILS,
  NAME_DESC_SKILL,
}

export enum CharacterSheetTab {
  SKILLS = "Habilidades",
  ITEMS = "Itens",
  OBJECTIVE = "Objetivo",
}
